DROP TABLE IF EXISTS user;


CREATE TABLE user (
	uid INTEGER PRIMARY KEY AUTOINCREMENT,
	uname TEXT UNIQUE NOT NULL,
	pass TEXT NOT NULL
);

CREATE TABLE todo (
	tid INTEGER PRIMARY KEY,
	uid INTEGER,
	FOREIGN KEY (uid) REFERENCES user(uid)
);

